# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/pool-root";
    fsType = "ext4";
  };

  fileSystems."/nix/var/nix/daemon-socket" = {
    device = "/nix/var/nix/daemon-socket";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/nix/var/nix/db" = {
    device = "/nix/var/nix/db";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/nix/var/nix/gcroots" = {
    device = "/nix/var/nix/gcroots/per-container/test";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/nix/var/nix/profiles" = {
    device = "/nix/var/nix/profiles/per-container/test";
    fsType = "none";
    options = ["bind"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  boot.isNspawnContainer = true;
}
